[package]
name = 'diffsolR'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'diffsolR'

[dependencies]
extendr-api = '*'
nalgebra = "0.33.2"
diffsol = { version = "0.5.0", features = ["diffsl"]}
take_mut = "0.2.2"
faer = "0.19.4"
